name: Hit Tweet API

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight (UTC)

jobs:
  hit-api:
    runs-on: ubuntu-latest

    steps:
    - name: Hit API
      run: |
        curl -X GET https://botxog.vercel.app/api/tweet
